import * as F from "@/core/functions";
import { m } from "@/core/sensing_properties";


export function getColorFromGradient(colors=["#000000","#ffffff"], factor=0) {
    factor = F.clamp(factor, 0, 1); // MINE
    // BELOW CODE GENERATED BY AI

    // If there's only one color, return it
    if (colors.length === 1) return colors[0];

    // Find the two colors to interpolate between
    const index = (colors.length - 1) * factor;
    const i = Math.floor(index);
    const t = index - i; // Relative position within the segment (0 to 1)

    const color1 = colors[i];
    const color2 = colors[Math.min(i + 1, colors.length - 1)];

    // Interpolate between the two colors (assuming hex format #RRGGBB)
    const rgb = [0, 1, 2].map(j => {
        const c1 = parseInt(color1.slice(1 + j * 2, 3 + j * 2), 16);
        const c2 = parseInt(color2.slice(1 + j * 2, 3 + j * 2), 16);
        return Math.round(c1 * (1 - t) + c2 * t);
    });

    // Convert RGB to hex
    return '#' + rgb.map(c => c.toString(16).padStart(2, '0')).join('');
}

interface AnimationParameter {
    duration: number,
    /** Time offset since the animation start. */
    offset?: number,

    onStart?: (t: AnimationTimeProperties)=>void,
    onTick?: (t: AnimationTimeProperties)=>void,
    /** If this callback is defined, it will be executed instead of `onTick()` when the animation part is finished. */
    onFinish?: (t: AnimationTimeProperties)=>void
}
interface AnimationParameterE extends AnimationParameter {
    offset: number
}
interface AnimationTimeProperties {
    time: number,
    totalTime: number,
    duration: number,
    percent: number
}

/**
 * An instance of the AnimationSequence class allows you to sequently 
 * and smoothly change the numbers for specified period of time assigned 
 * to mutable data types or, in simple terms, to play smooth animations 
 * of object positions and states.
 */
export class AnimationSequence {
    animationList: AnimationParameterE[] = [];

    private idleAnimations = new Set<AnimationParameterE>();
    private playingAnimations = new Set<AnimationParameterE>();

    /** Time in seconds since an animation has started. */
    totalTime = 0;
    /** Whether the animation is playing. If this property is false, the animation has paused or stopped. */
    playing = false;
    /** Whether the animation can be played again using `startOnce()`. */
    canStart = true;

    /** Executed at the start of the animation. Call this method to set the initial state immediately. */
    public onStart?: ()=>void;
    constructor(onStart?: ()=>void) {
        this.onStart = onStart;
    }

    /** A builder method. */
    createState(properties: AnimationParameter) {
        this.animationList.push({
            duration: properties.duration,
            offset: properties.offset ?? 0,
            onStart: properties.onStart,
            onTick: properties.onTick,
            onFinish: properties.onFinish
        });
        return this;
    }

    start(noFirstTick=false, timeOffset=0) {
        this.playing = true;
        this.totalTime = timeOffset;

        for (const animation of this.animationList) {
            this.idleAnimations.add(animation);
        }
        this.playingAnimations.clear();

        if (this.onStart) {
            this.onStart();
        }
        
        if (!noFirstTick) {
            for (const animation of this.animationList.filter((el)=>(el.offset === 0))) {
                if (animation.onTick) {
                    animation.onTick(this.getTimeProperty(animation, (timeOffset)));
                }
            } 
        }
    }

    /** Controlled by the property `canStart`. */
    startOnce(noFirstTick=false, timeOffset=0) {
        if (this.canStart) {
            this.canStart = false;
            this.start(noFirstTick, timeOffset);
        }
    }

    stop() {
        this.playing = false;
    }

    /** An essential method for handling animation. When not called, the animation is paused. */
    simulateTick() {
        if (this.playing) {
            this.totalTime += m.delta;

            // handle idle animations
            for (const animation of this.idleAnimations.values()) {
                if (this.totalTime >= animation.offset) {
                    this.idleAnimations.delete(animation);
                    this.playingAnimations.add(animation);

                    if (animation.onStart) {
                        animation.onStart(this.getTimeProperty(animation, (this.totalTime - animation.offset)));
                    }
                }
            }

            // handle playing animations
            for (const animation of this.playingAnimations.values()) {
                if (this.totalTime >= animation.offset+animation.duration) {
                    // animation has finished
                    this.playingAnimations.delete(animation);
                    if (this.idleAnimations.size === 0 && this.playingAnimations.size === 0) {
                        this.playing = false;
                    }

                    if (animation.onFinish) {
                        animation.onFinish(this.getTimeProperty(animation, (animation.duration)));
                    }
                    else if (animation.onTick) {
                        animation.onTick(this.getTimeProperty(animation, (animation.duration)));
                    }
                }
                else {
                    // animation is playing
                    if (animation.onTick) {
                        animation.onTick(this.getTimeProperty(animation, (this.totalTime - animation.offset)));
                    }
                }
            }
        }
    }

    private getTimeProperty(anim: AnimationParameterE, time: number): AnimationTimeProperties {
        return {
            time: time,
            totalTime: this.totalTime,
            duration: anim.duration,
            percent: (anim.duration > 0) ? time/anim.duration : 0
        }
    }
}
